name: "[Backend] Build + Unit & Component tests"
on:
  push:
    branches: [main, master, dev]
  pull_request:
    branches: [main, master, dev]
jobs:
  test:
    timeout-minutes: 60
    runs-on: ubuntu-latest
    services:
      postgres:
        image: bitnami/postgresql:latest
        env:
          POSTGRESQL_USERNAME: user
          POSTGRESQL_PASSWORD: password123
          POSTGRESQL_DATABASE: studystorm
        ports:
          - 5432:5432
    env:
      PG_HOST: postgres
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: "16.x"
      - name: Install dependencies
        run: yarn install
      - name: Build output
        run: yarn build
      - name: Run tests
        run: yarn test
